---
project_name: actions
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod tidy
    - sed -i "s/PLACEHOLDER_BINARY_NAME/{{ .ProjectName }}/g" Dockerfile_copy
builds:
  # the majority of bins
  - id: actions
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
  # only support windows_amd64
  - id: actions_windows
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    id: binary
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# dockers:
#   - image_templates:
#       - "ghcr.io/intrand/{{ .ProjectName }}:{{ .Version }}-amd64"
#     dockerfile: Dockerfile_copy
#     use: buildx
#     build_flag_templates:
#       - --platform=linux/amd64
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description={{ .ProjectName }}
#       - --label=org.opencontainers.image.url=https://github.com/intrand/{{ .ProjectName }}
#       - --label=org.opencontainers.image.source=https://github.com/intrand/{{ .ProjectName }}
#       - --label=org.opencontainers.image.version={{ .Version }}
#       - --label=org.opencontainers.image.created={{ time "2022-01-27T00:00:00Z00:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT
#   - image_templates:
#       - "ghcr.io/intrand/{{ .ProjectName }}:{{ .Version }}-arm64v8"
#     goarch: arm64
#     dockerfile: Dockerfile_copy
#     use: buildx
#     build_flag_templates:
#       - --platform=linux/arm64/v8
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description={{ .ProjectName }}
#       - --label=org.opencontainers.image.url=https://github.com/intrand/{{ .ProjectName }}
#       - --label=org.opencontainers.image.source=https://github.com/intrand/{{ .ProjectName }}
#       - --label=org.opencontainers.image.version={{ .Version }}
#       - --label=org.opencontainers.image.created={{ time "2022-01-27T00:00:00Z00:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT
# docker_manifests:
#   - name_template: "ghcr.io/intrand/{{ .ProjectName }}:{{ .Version }}"
#     image_templates:
#       - "ghcr.io/intrand/{{ .ProjectName }}:{{ .Version }}-amd64"
#       - "ghcr.io/intrand/{{ .ProjectName }}:{{ .Version }}-arm64v8"
