---
name: actions

on:
  push:
    tags:
      - "*" # triggers on all new tags

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: docker login
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: git checkout
      #   uses: actions/checkout@v2.4.0
      #   with:
      #     fetch-depth: 0

      # - name: set up qemu
      #   uses: docker/setup-qemu-action@v1.2.0

      # - name: set up docker buildx
      #   uses: docker/setup-buildx-action@v1.6.0

      # - name: docker login
      #   uses: docker/login-action@v1.12.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: setup-go
      #   uses: actions/setup-go@v2.1.5
      #   with:
      #     go-version: 1.17

      # - name: goreleaser
      #   uses: goreleaser/goreleaser-action@v2.8.1
      #   with:
      #     version: latest
      #     args: release
      #     # --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
