---
name: actions

on: push

jobs:
  date:
    if: ${{ false }}
    runs-on: ubuntu-latest
    env:
      TZ: UTC0
    outputs:
      date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: get_date
        run: echo "::set-output name=date::$(git show -s --format=%cdZ --date=format-local:'%Y-%m-%dT%H:%M:%S')" # 2022-01-28T16:21:36Z

  show:
    if: ${{ false }}
    needs: date
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.date.outputs.date}}
