---
name: actions

on:
  push:
    tags:
      - "*" # triggers on all new tags

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: setup-go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
